spring:
  application:
    name: notetaking

  datasource:
    url: ${POSTGRESQL_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  liquibase:
    change-log: classpath:db/changelog/changelog.xml
    enabled: true
